import {
  LayoutDashboard,
  ShoppingCart,
  Wallet,
  Settings2,
  Users,
  Package,
  CreditCard,
  Truck,
  HardHat,
  Settings,
  // Submenu icons
  Monitor,
  PlusCircle,
  ClipboardList,
  BarChart3,
  UserCheck,
  Calendar,
  Receipt,
  Gauge,
  Activity,
  Map,
  Bell,
  Route,
  CalendarDays,
  Search,
  Brain,
  FileText,
  Target,
  CalendarRange,
  DollarSign,
  Store,
  Factory,
  UserPlus,
  Megaphone,
  Heart,
  MessageSquare,
  Trophy,
  PackageOpen,
  ShoppingBag,
  ShoppingBasket,
  Handshake,
  TrendingUp,
  TrendingDown,
  ArrowUpDown,
  HandCoins,
  CheckSquare,
  FileSpreadsheet,
  Calculator,
  Users2,
  Ticket,
  BadgeCheck,
  ShieldCheck,
  Car,
  Fuel,
  Wrench,
  BarChart,
  Gamepad2,
  UserCog,
  Banknote,
  CreditCard as CreditCardIcon,
  Award,
  Gift,
  Clock,
  Timer,
  CalendarClock,
  ShieldAlert,
  Zap,
  Cog,
  Lock,
  ClipboardCheck,
  Fingerprint,
  FileWarning,
  Star,
  UserCheck as UserCheckIcon,
  BarChart2,
  type LucideIcon,
} from "lucide-react";

export interface SubMenuItem {
  icon: LucideIcon;
  label: string;
  path: string;
}

export interface MenuItem {
  icon: LucideIcon;
  label: string;
  path?: string;
  submenu?: SubMenuItem[];
}

export const menuItems: MenuItem[] = [
  { icon: LayoutDashboard, label: "Dashboard", path: "/" },
  { icon: Brain, label: "Assistente IA", path: "/assistente-ia" },
  {
    icon: ShoppingCart,
    label: "Vendas",
    submenu: [
      { icon: Monitor, label: "PDV", path: "/vendas/pdv" },
      { icon: PlusCircle, label: "Nova Venda", path: "/vendas/nova" },
      { icon: ClipboardList, label: "Pedidos", path: "/vendas/pedidos" },
      { icon: BarChart3, label: "Relatório de Vendas", path: "/vendas/relatorio" },
    ],
  },
  {
    icon: Wallet,
    label: "Caixa",
    submenu: [
      { icon: UserCheck, label: "Acerto Diário Entregador", path: "/caixa/acerto" },
      { icon: Calendar, label: "Caixa do Dia", path: "/caixa/dia" },
      { icon: Receipt, label: "Despesas (Sangria)", path: "/caixa/despesas" },
    ],
  },
  {
    icon: Settings2,
    label: "Gestão Operacional",
    submenu: [
      { icon: Gauge, label: "Cockpit do Gestor", path: "/operacional/cockpit" },
      { icon: Activity, label: "Central de Indicadores", path: "/operacional/indicadores" },
      { icon: Map, label: "Mapa Operacional", path: "/operacional/centro" },
      { icon: Bell, label: "Alertas Inteligentes", path: "/operacional/alertas" },
      { icon: Route, label: "Rotas de Entrega", path: "/operacional/rotas" },
      { icon: CalendarDays, label: "Escalas de Entregadores", path: "/operacional/escalas" },
      { icon: FileSpreadsheet, label: "Análise de Resultados", path: "/operacional/analise-resultados" },
      { icon: CalendarRange, label: "Planejamento", path: "/operacional/planejamento" },
      { icon: Target, label: "Metas e Desafios", path: "/operacional/metas" },
      { icon: Search, label: "Análise de Concorrência", path: "/operacional/concorrencia" },
    ],
  },
  {
    icon: Users,
    label: "Gestão de Clientes",
    submenu: [
      { icon: UserPlus, label: "Clientes", path: "/clientes/cadastro" },
      { icon: Megaphone, label: "Campanhas", path: "/clientes/campanhas" },
      { icon: Heart, label: "Fidelidade / Indicações", path: "/clientes/fidelidade" },
      { icon: MessageSquare, label: "CRM", path: "/clientes/crm" },
      { icon: Trophy, label: "Ranking dos Clientes", path: "/clientes/ranking" },
    ],
  },
  {
    icon: Package,
    label: "Gestão de Estoque",
    submenu: [
      { icon: Gauge, label: "Dashboard", path: "/estoque/dashboard" },
      { icon: PackageOpen, label: "Estoque do Dia", path: "/estoque" },
      { icon: ShoppingBag, label: "Produtos", path: "/cadastros/produtos" },
      { icon: ShoppingBasket, label: "Compras", path: "/estoque/compras" },
      { icon: Factory, label: "Fornecedores", path: "/cadastros/fornecedores" },
      { icon: Handshake, label: "Comodatos", path: "/estoque/comodatos" },
      { icon: ArrowUpDown, label: "Transferência entre Filiais", path: "/estoque/transferencia" },
      { icon: TrendingUp, label: "MCMM Inteligente", path: "/estoque/mcmm" },
      { icon: ClipboardList, label: "Histórico Movimentações", path: "/estoque/historico" },
    ],
  },
  {
    icon: CreditCard,
    label: "Gestão Financeira",
    submenu: [
      { icon: Gauge, label: "Dashboard", path: "/financeiro" },
      { icon: ArrowUpDown, label: "Fluxo de Caixa", path: "/financeiro/fluxo" },
      { icon: TrendingDown, label: "Previsão de Caixa", path: "/financeiro/previsao" },
      { icon: HandCoins, label: "Contas a Pagar", path: "/financeiro/pagar" },
      { icon: Banknote, label: "Contas a Receber", path: "/financeiro/receber" },
      { icon: CheckSquare, label: "Aprovar Despesas", path: "/financeiro/aprovar" },
      { icon: FileSpreadsheet, label: "Conciliação (OFX / CSV)", path: "/financeiro/conciliacao" },
      { icon: Calculator, label: "Contador", path: "/financeiro/contador" },
      { icon: CreditCardIcon, label: "Terminais de Cartão", path: "/financeiro/terminais" },
      { icon: Banknote, label: "Emissão de Boletos", path: "/financeiro/boletos" },
      { icon: TrendingDown, label: "Aging Report", path: "/financeiro/aging" },
      { icon: CalendarDays, label: "Calendário Financeiro", path: "/financeiro/calendario" },
      { icon: Users2, label: "Vale Gás - Parceiros", path: "/financeiro/vale-gas/parceiros" },
      { icon: Ticket, label: "Vale Gás - Emissão", path: "/financeiro/vale-gas/emissao" },
      { icon: BadgeCheck, label: "Vale Gás - Controle", path: "/financeiro/vale-gas/controle" },
      { icon: ShieldCheck, label: "Vale Gás - Acerto", path: "/financeiro/vale-gas/acerto" },
      { icon: BarChart, label: "Vale Gás - Relatório", path: "/financeiro/vale-gas/relatorio" },
    ],
  },
  {
    icon: Truck,
    label: "Gestão de Frota",
    submenu: [
      { icon: Gauge, label: "Dashboard", path: "/frota" },
      { icon: Car, label: "Veículos", path: "/cadastros/veiculos" },
      { icon: Fuel, label: "Controle de Combustível", path: "/frota/combustivel" },
      { icon: Wrench, label: "Manutenção", path: "/frota/manutencao" },
      { icon: ShieldCheck, label: "Documentos", path: "/frota/documentos" },
      { icon: ClipboardCheck, label: "Checklist de Saída", path: "/frota/checklist" },
      { icon: FileWarning, label: "Multas", path: "/frota/multas" },
      { icon: BarChart3, label: "Relatórios", path: "/frota/relatorios" },
      { icon: Gamepad2, label: "Gamificação", path: "/frota/gamificacao" },
    ],
  },
  {
    icon: HardHat,
    label: "Gestão de RH",
    submenu: [
      { icon: BarChart2, label: "Dashboard RH", path: "/rh/dashboard" },
      { icon: UserCog, label: "Funcionários", path: "/cadastros/funcionarios" },
      { icon: Truck, label: "Entregadores", path: "/cadastros/entregadores" },
      { icon: Banknote, label: "Folha de Pagamento", path: "/rh/folha" },
      { icon: Fingerprint, label: "Ponto Eletrônico", path: "/rh/ponto" },
      { icon: CreditCardIcon, label: "Vale Funcionário", path: "/rh/vale" },
      { icon: DollarSign, label: "Comissão do Entregador", path: "/rh/comissao" },
      { icon: Award, label: "Premiação", path: "/rh/premiacao" },
      { icon: Gift, label: "Bônus", path: "/rh/bonus" },
      { icon: Clock, label: "Alerta Jornada", path: "/rh/jornada" },
      { icon: Timer, label: "Banco de Horas", path: "/rh/banco-horas" },
      { icon: CalendarClock, label: "Horários", path: "/rh/horarios" },
      { icon: CalendarDays, label: "Controle de Férias", path: "/rh/ferias" },
      { icon: FileWarning, label: "Atestados e Faltas", path: "/rh/atestados" },
      { icon: Star, label: "Avaliação de Desempenho", path: "/rh/avaliacao" },
      { icon: UserCheckIcon, label: "Onboarding / Offboarding", path: "/rh/onboarding" },
      { icon: ShieldAlert, label: "Prevenção Trabalhista - IA", path: "/rh/prevencao-ia" },
      { icon: Zap, label: "Produtividade - IA", path: "/rh/produtividade-ia" },
    ],
  },
  {
    icon: FileText,
    label: "Gestão Fiscal",
    submenu: [
      { icon: Receipt, label: "Emitir NF-e", path: "/fiscal/nfe" },
      { icon: Monitor, label: "Emitir NFC-e", path: "/fiscal/nfce" },
      { icon: Truck, label: "Emitir MDF-e", path: "/fiscal/mdfe" },
      { icon: Route, label: "Emitir CT-e", path: "/fiscal/cte" },
      { icon: FileSpreadsheet, label: "Gerar XML", path: "/fiscal/xml" },
      { icon: BarChart3, label: "Relatórios de Notas", path: "/fiscal/relatorios" },
    ],
  },
  {
    icon: Settings,
    label: "Configurações",
    submenu: [
      { icon: Cog, label: "Geral / Regras", path: "/configuracoes" },
      { icon: Users2, label: "Usuários", path: "/config/usuarios" },
      { icon: Store, label: "Unidades / Lojas", path: "/config/unidades" },
      { icon: ClipboardCheck, label: "Auditoria", path: "/config/auditoria" },
      { icon: Lock, label: "Permissões", path: "/config/permissoes" },
      { icon: FileSpreadsheet, label: "Categorias de Despesas", path: "/config/categorias-despesa" },
      { icon: FileText, label: "Documentos da Empresa", path: "/config/documentos" },
      { icon: Megaphone, label: "Canais de Venda", path: "/operacional/canais-venda" },
    ],
  },
];
